server:
  port: 8082
spring:
  application:
    name: meeting-demo
dubbo:
  scan:
    base-packages: com.yonyou.meeting
  application:
    name: dubbo-gateway
    id: dubbo-gateway
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
    check: false