server:
  port: 8081
spring:
  application:
    name: service-demo
dubbo:
  scan:
    base-packages: com.yonyou.meeting.service.demo.service
  application:
    name: dubbo-service-demo
    id: dubbo-service-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
    check: false